/*
 * Ramon - A RMON2 Network Monitoring Agent
 * Copyright (C) 2003 Ricardo Nabinger Sanchez
 *
 * This file is part of Ramon, a network monitoring agent which implements
 * the MIB proposed in RFC-2021.
 *
 * Ramon is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
 *
 * Ramon is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with program; see the file COPYING. If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "alMatrix.h"

#include "pedb.h"
#include "almatrix_DS.h"
#include "almatrix_SD.h"
#include "exit_codes.h"

/** Initialize the alMatrixSDTable table by defining its contents and how it's structured */
void
initialize_table_alMatrixSDTable(void)
{
    static oid alMatrixSDTable_oid[] = { 1, 3, 6, 1, 2, 1, 16, 17, 1 };
    netsnmp_table_registration_info *table_info;
    netsnmp_handler_registration    *my_handler;
    netsnmp_iterator_info	    *iinfo;

    /*
     * create the table structure itself
     */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);

    /*
     * if your table is read only, it's easiest to change the
     * HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY
     */
    my_handler = netsnmp_create_handler_registration("alMatrixSDTable",
                                                     alMatrixSDTable_handler,
                                                     alMatrixSDTable_oid,
                                                     OID_LENGTH(alMatrixSDTable_oid),
                                                     HANDLER_CAN_RONLY);

    if (!my_handler || !table_info || !iinfo)
        return;                 /* mallocs failed */

    /***************************************************
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(table_info,
				     ASN_INTEGER,   /* index: hlMatrixControlIndex */
                                     ASN_TIMETICKS,     /* index: alMatrixSDTimeMark */
                                     ASN_INTEGER,       /* index: protocolDirLocalIndex */
                                     ASN_OCTET_STR,     /* index: nlMatrixSDSourceAddress */
                                     ASN_OCTET_STR,     /* index: nlMatrixSDDestAddress */
                                     ASN_INTEGER,       /* index: protocolDirLocalIndex */
                                     0);

    table_info->min_column = 2;
    table_info->max_column = 4;

    /*
     * iterator access routines
     */
    iinfo->get_first_data_point = alMatrixSDTable_get_first_data_point;
    iinfo->get_next_data_point = alMatrixSDTable_get_next_data_point;

    iinfo->table_reginfo = table_info;

    /***************************************************
     * registering the table with the master agent
     */
    DEBUGMSGTL(("initialize_table_alMatrixSDTable",
                "Registering table alMatrixSDTable as a table iterator\n"));
    netsnmp_register_table_iterator(my_handler, iinfo);

    snmp_log(LOG_INFO, "success: alMatrixSD initialized\n");
}


/** Initialize the alMatrixTopNControlTable table by defining its contents and how it's structured */
void
initialize_table_alMatrixTopNControlTable(void)
{
    static oid alMatrixTopNControlTable_oid[] = { 1, 3, 6, 1, 2, 1, 16, 17, 3 };
    netsnmp_table_registration_info *table_info;
    netsnmp_handler_registration    *my_handler;
    netsnmp_iterator_info	    *iinfo;

    /*
     * create the table structure itself
     */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);

    /*
     * if your table is read only, it's easiest to change the
     * HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY
     */
    my_handler =
        netsnmp_create_handler_registration("alMatrixTopNControlTable",
                                            alMatrixTopNControlTable_handler,
                                            alMatrixTopNControlTable_oid,
                                            OID_LENGTH(alMatrixTopNControlTable_oid),
                                            HANDLER_CAN_RWRITE);

    if (!my_handler || !table_info || !iinfo)
        return;                 /* mallocs failed */

    /***************************************************
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(table_info,
				     ASN_INTEGER,   /* index: alMatrixTopNControlIndex */
                                     0);

    table_info->min_column = 2;
    table_info->max_column = 11;

    /*
     * iterator access routines
     */
    iinfo->get_first_data_point =
        alMatrixTopNControlTable_get_first_data_point;
    iinfo->get_next_data_point =
        alMatrixTopNControlTable_get_next_data_point;

    iinfo->table_reginfo = table_info;

    /***************************************************
     * registering the table with the master agent
     */
    DEBUGMSGTL(("initialize_table_alMatrixTopNControlTable",
                "Registering table alMatrixTopNControlTable as a table iterator\n"));
    netsnmp_register_table_iterator(my_handler, iinfo);
}


/** Initialize the alMatrixTopNTable table by defining its contents and how it's structured */
void
initialize_table_alMatrixTopNTable(void)
{
    static oid alMatrixTopNTable_oid[] = { 1, 3, 6, 1, 2, 1, 16, 17, 4 };
    netsnmp_table_registration_info *table_info;
    netsnmp_handler_registration    *my_handler;
    netsnmp_iterator_info	    *iinfo;

    /*
     * create the table structure itself
     */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);

    /*
     * if your table is read only, it's easiest to change the
     * HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY
     */
    my_handler = netsnmp_create_handler_registration("alMatrixTopNTable",
                                                     alMatrixTopNTable_handler,
                                                     alMatrixTopNTable_oid,
                                                     OID_LENGTH(alMatrixTopNTable_oid),
                                                     HANDLER_CAN_RONLY);

    if (!my_handler || !table_info || !iinfo)
        return;                 /* mallocs failed */

    /***************************************************
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: alMatrixTopNControlIndex */
                                     ASN_INTEGER,       /* index: alMatrixTopNIndex */
                                     0);

    table_info->min_column = 2;
    table_info->max_column = 9;

    /*
     * iterator access routines
     */
    iinfo->get_first_data_point = alMatrixTopNTable_get_first_data_point;
    iinfo->get_next_data_point = alMatrixTopNTable_get_next_data_point;

    iinfo->table_reginfo = table_info;

    /***************************************************
     * registering the table with the master agent
     */
    DEBUGMSGTL(("initialize_table_alMatrixTopNTable",
                "Registering table alMatrixTopNTable as a table iterator\n"));
    netsnmp_register_table_iterator(my_handler, iinfo);
}


/** Initialize the alMatrixDSTable table by defining its contents and how it's structured */
void
initialize_table_alMatrixDSTable(void)
{
    static oid alMatrixDSTable_oid[] = { 1, 3, 6, 1, 2, 1, 16, 17, 2 };
    netsnmp_table_registration_info *table_info;
    netsnmp_handler_registration    *my_handler;
    netsnmp_iterator_info	    *iinfo;

    /*
     * create the table structure itself
     */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);

    /*
     * if your table is read only, it's easiest to change the
     * HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY
     */
    my_handler = netsnmp_create_handler_registration("alMatrixDSTable",
                                                     alMatrixDSTable_handler,
                                                     alMatrixDSTable_oid,
                                                     OID_LENGTH(alMatrixDSTable_oid),
                                                     HANDLER_CAN_RONLY);

    if (!my_handler || !table_info || !iinfo)
        return;                 /* mallocs failed */

    /***************************************************
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(table_info,
				     ASN_INTEGER,   /* index: hlMatrixControlIndex */
                                     ASN_TIMETICKS,     /* index: alMatrixDSTimeMark */
                                     ASN_INTEGER,       /* index: protocolDirLocalIndex */
                                     ASN_OCTET_STR,     /* index: nlMatrixDSDestAddress */
                                     ASN_OCTET_STR,     /* index: nlMatrixDSSourceAddress */
                                     ASN_INTEGER,       /* index: protocolDirLocalIndex */
                                     0);

    table_info->min_column = 2;
    table_info->max_column = 4;

    /*
     * iterator access routines
     */
    iinfo->get_first_data_point = alMatrixDSTable_get_first_data_point;
    iinfo->get_next_data_point = alMatrixDSTable_get_next_data_point;

    iinfo->table_reginfo = table_info;

    /***************************************************
     * registering the table with the master agent
     */
    DEBUGMSGTL(("initialize_table_alMatrixDSTable",
                "Registering table alMatrixDSTable as a table iterator\n"));
    netsnmp_register_table_iterator(my_handler, iinfo);

    snmp_log(LOG_INFO, "success: alMatrixDS initialized\n");
}


/** Initializes the alMatrix module */
void
init_alMatrix(void)
{

    /*
     * here we initialize all the tables we're planning on supporting
     */
    initialize_table_alMatrixSDTable();
//    initialize_table_alMatrixTopNControlTable();
//    initialize_table_alMatrixTopNTable();
    initialize_table_alMatrixDSTable();
}


/** returns the first data point within the alMatrixSDTable table data.

    Set the my_loop_context variable to the first data point structure
    of your choice (from which you can find the next one).  This could
    be anything from the first node in a linked list, to an integer
    pointer containing the beginning of an array variable.

    Set the my_data_context variable to something to be returned to
    you later that will provide you with the data to return in a given
    row.  This could be the same pointer as what my_loop_context is
    set to, or something different.

    The put_index_data variable contains a list of snmp variable
    bindings, one for each index in your table.  Set the values of
    each appropriately according to the data matching the first row
    and return the put_index_data variable at the end of the function.
*/
netsnmp_variable_list *
alMatrixSDTable_get_first_data_point(void **my_loop_context,
                                     void **my_data_context,
                                     netsnmp_variable_list *put_index_data,
                                     netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    uint32_t		    indice;
    uint32_t		    tripa[6];

    if (almatrix_sd_tabela_prepara(&indice) != SUCCESS) {
	return NULL;
    }

    if (almatrix_sd_helper(indice, &tripa[0], &tripa[1], &tripa[2],
		&tripa[3], &tripa[4], &tripa[5]) != SUCCESS) {
	return NULL;
    }

    *my_loop_context = (void *)indice;
    *my_data_context = (void *)indice;

    vptr = put_index_data;

    snmp_set_var_value(vptr, (u_char *)&tripa[0], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[1], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[2], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[3], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[4], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[5], sizeof(uint32_t));

    vptr = vptr->next_variable;

    return put_index_data;
}


/** functionally the same as alMatrixSDTable_get_first_data_point, but
   my_loop_context has already been set to a previous value and should
   be updated to the next in the list.  For example, if it was a
   linked list, you might want to cast it and the return
   my_loop_context->next.  The my_data_context pointer should be set
   to something you need later and the indexes in put_index_data
   updated again. */

netsnmp_variable_list *
alMatrixSDTable_get_next_data_point(void **my_loop_context,
                                    void **my_data_context,
                                    netsnmp_variable_list *put_index_data,
                                    netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    uint32_t		    indice;
    uint32_t		    tripa[6];

    if (almatrix_sd_tabela_proximo(&indice) != SUCCESS) {
	return NULL;
    }

    if (almatrix_sd_helper(indice, &tripa[0], &tripa[1], &tripa[2],
		&tripa[3], &tripa[4], &tripa[5]) != SUCCESS) {
	return NULL;
    }

    *my_loop_context = (void *)indice;
    *my_data_context = (void *)indice;

    vptr = put_index_data;

    snmp_set_var_value(vptr, (u_char *)&tripa[0], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[1], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[2], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[3], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[4], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[5], sizeof(uint32_t));

    vptr = vptr->next_variable;

    return put_index_data;
}


/** handles requests for the alMatrixSDTable table, if anything else needs to be done */
int
alMatrixSDTable_handler(netsnmp_mib_handler *handler,
                        netsnmp_handler_registration *reginfo,
                        netsnmp_agent_request_info *reqinfo,
                        netsnmp_request_info *requests)
{
    netsnmp_request_info	*request;
    netsnmp_table_request_info	*table_info;
    netsnmp_variable_list	*var;
    uint32_t			indice;
    uint32_t			valor;

    for (request = requests; request; request = request->next) {
        var = request->requestvb;
        if (request->processed != 0)
            continue;

        /*
         * perform anything here that you need to do before each
         * request is processed.
         */

        /*
         * the following extracts the my_data_context pointer set in
         * the loop functions above.  You can then use the results to
         * help return data for the columns of the alMatrixSDTable table in question
         */

	indice = (uint32_t)netsnmp_extract_iterator_context(request);
        if (almatrix_sd_testa(indice) != SUCCESS) {
            if (reqinfo->mode == MODE_GET) {
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                continue;
            }
            /*
             * XXX: no row existed, if you support creation and this is a
             * set, start dealing with it here, else continue
             */

	    netsnmp_set_request_error(reqinfo, request, SNMP_ERR_NOCREATION);
	    return SNMP_ERR_NOCREATION;
        }

        /*
         * extracts the information about the table from the request
         */
        table_info = netsnmp_extract_table_info(request);
        /*
         * table_info->colnum contains the column number requested
         */
        /*
         * table_info->indexes contains a linked list of snmp variable
         * bindings for the indexes of the table.  Values in the list
         * have been set corresponding to the indexes of the
         * request
         */
        if (table_info == NULL) {
            continue;
        }

        switch (reqinfo->mode) {
            /*
             * the table_iterator helper should change all GETNEXTs
             * into GETs for you automatically, so you don't have to
             * worry about the GETNEXT case.  Only GETs and SETs need
             * to be dealt with here
             */
        case MODE_GET:
            switch (table_info->colnum) {
            case COLUMN_ALMATRIXSDPKTS:
		if (almatrix_sd_busca_pkts(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_GAUGE, (u_char *)&valor, sizeof(valor));
                break;

            case COLUMN_ALMATRIXSDOCTETS:
		if (almatrix_sd_busca_octets(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_GAUGE, (u_char *)&valor, sizeof(valor));
                break;

            case COLUMN_ALMATRIXSDCREATETIME:
		if (almatrix_sd_busca_createtime(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_TIMETICKS, (u_char *)&valor, sizeof(valor));
                break;

            default:
                /*
                 * We shouldn't get here
                 */
                snmp_log(LOG_ERR,
                         "problem encountered in alMatrixSDTable_handler: unknown column\n");
            }
            break;

        case MODE_SET_RESERVE1:
            /*
             * set handling...
             */

        default:
            snmp_log(LOG_ERR,
                     "problem encountered in alMatrixSDTable_handler: unsupported mode\n");
        }
    }
    return SNMP_ERR_NOERROR;
}


/** returns the first data point within the alMatrixTopNControlTable table data.

    Set the my_loop_context variable to the first data point structure
    of your choice (from which you can find the next one).  This could
    be anything from the first node in a linked list, to an integer
    pointer containing the beginning of an array variable.

    Set the my_data_context variable to something to be returned to
    you later that will provide you with the data to return in a given
    row.  This could be the same pointer as what my_loop_context is
    set to, or something different.

    The put_index_data variable contains a list of snmp variable
    bindings, one for each index in your table.  Set the values of
    each appropriately according to the data matching the first row
    and return the put_index_data variable at the end of the function.
*/
netsnmp_variable_list *
alMatrixTopNControlTable_get_first_data_point(void **my_loop_context,
                                              void **my_data_context,
                                              netsnmp_variable_list *put_index_data,
                                              netsnmp_iterator_info *mydata)
{
    /* not supported yet */
    return NULL;
#if 0
    netsnmp_variable_list *vptr;

    *my_loop_context = /* XXX */ ;
    *my_data_context = /* XXX */ ;

    vptr = put_index_data;

    snmp_set_var_value(vptr,
                       (u_char *) /* XXX: alMatrixTopNControlIndex data */
                       , /* XXX: length of alMatrixTopNControlIndex data */
                       );
    vptr = vptr->next_variable;

    return put_index_data;
#endif
}


/** functionally the same as alMatrixTopNControlTable_get_first_data_point, but
   my_loop_context has already been set to a previous value and should
   be updated to the next in the list.  For example, if it was a
   linked list, you might want to cast it and the return
   my_loop_context->next.  The my_data_context pointer should be set
   to something you need later and the indexes in put_index_data
   updated again. */

netsnmp_variable_list *
alMatrixTopNControlTable_get_next_data_point(void **my_loop_context,
                                             void **my_data_context,
                                             netsnmp_variable_list *put_index_data,
                                             netsnmp_iterator_info *mydata)
{
    return NULL;
#if 0
    netsnmp_variable_list *vptr;

    *my_loop_context = /* XXX */ ;
    *my_data_context = /* XXX */ ;

    vptr = put_index_data;

    snmp_set_var_value(vptr,
                       (u_char *) /* XXX: alMatrixTopNControlIndex data */
                       , /* XXX: length of alMatrixTopNControlIndex data */
                       );
    vptr = vptr->next_variable;

    return put_index_data;
#endif
}


/** handles requests for the alMatrixTopNControlTable table, if anything else needs to be done */
int
alMatrixTopNControlTable_handler(netsnmp_mib_handler *handler,
                                 netsnmp_handler_registration *reginfo,
                                 netsnmp_agent_request_info *reqinfo,
                                 netsnmp_request_info *requests)
{
#if 0
    netsnmp_request_info *request;
    netsnmp_table_request_info *table_info;
    netsnmp_variable_list *var;

    for (request = requests; request; request = request->next) {
        var = request->requestvb;
        if (request->processed != 0)
            continue;

        /*
         * perform anything here that you need to do before each
         * request is processed.
         */

        /*
         * the following extracts the my_data_context pointer set in
         * the loop functions above.  You can then use the results to
         * help return data for the columns of the alMatrixTopNControlTable table in question
         */
        /*
         * XXX
         */  = ( /* XXX */ *)netsnmp_extract_iterator_context(request);
        if ( /* XXX */  == NULL) {
            if (reqinfo->mode == MODE_GET) {
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHINSTANCE);
                continue;
            }
            /*
             * XXX: no row existed, if you support creation and this is a
             * set, start dealing with it here, else continue
             */
        }

        /*
         * extracts the information about the table from the request
         */
        table_info = netsnmp_extract_table_info(request);
        /*
         * table_info->colnum contains the column number requested
         */
        /*
         * table_info->indexes contains a linked list of snmp variable
         * bindings for the indexes of the table.  Values in the list
         * have been set corresponding to the indexes of the
         * request
         */
        if (table_info == NULL) {
            continue;
        }

        switch (reqinfo->mode) {
            /*
             * the table_iterator helper should change all GETNEXTs
             * into GETs for you automatically, so you don't have to
             * worry about the GETNEXT case.  Only GETs and SETs need
             * to be dealt with here
             */
        case MODE_GET:
            switch (table_info->colnum) {
            case COLUMN_ALMATRIXTOPNCONTROLMATRIXINDEX:
                snmp_set_var_typed_value(var, ASN_INTEGER,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNCONTROLRATEBASE:
                snmp_set_var_typed_value(var, ASN_INTEGER,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNCONTROLTIMEREMAINING:
                snmp_set_var_typed_value(var, ASN_INTEGER,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNCONTROLGENERATEDREPORTS:
                snmp_set_var_typed_value(var, ASN_COUNTER,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNCONTROLDURATION:
                snmp_set_var_typed_value(var, ASN_INTEGER,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNCONTROLREQUESTEDSIZE:
                snmp_set_var_typed_value(var, ASN_INTEGER,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNCONTROLGRANTEDSIZE:
                snmp_set_var_typed_value(var, ASN_INTEGER,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNCONTROLSTARTTIME:
                snmp_set_var_typed_value(var, ASN_TIMETICKS,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNCONTROLOWNER:
                snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNCONTROLSTATUS:
                snmp_set_var_typed_value(var, ASN_INTEGER,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            default:
                /*
                 * We shouldn't get here
                 */
                snmp_log(LOG_ERR,
                         "problem encountered in alMatrixTopNControlTable_handler: unknown column\n");
            }
            break;

        case MODE_SET_RESERVE1:
            /*
             * set handling...
             */

        default:
            snmp_log(LOG_ERR,
                     "problem encountered in alMatrixTopNControlTable_handler: unsupported mode\n");
        }
    }
#endif
    return SNMP_ERR_NOERROR;
}


/** returns the first data point within the alMatrixTopNTable table data.

    Set the my_loop_context variable to the first data point structure
    of your choice (from which you can find the next one).  This could
    be anything from the first node in a linked list, to an integer
    pointer containing the beginning of an array variable.

    Set the my_data_context variable to something to be returned to
    you later that will provide you with the data to return in a given
    row.  This could be the same pointer as what my_loop_context is
    set to, or something different.

    The put_index_data variable contains a list of snmp variable
    bindings, one for each index in your table.  Set the values of
    each appropriately according to the data matching the first row
    and return the put_index_data variable at the end of the function.
*/
netsnmp_variable_list *
alMatrixTopNTable_get_first_data_point(void **my_loop_context,
                                       void **my_data_context,
                                       netsnmp_variable_list *put_index_data,
                                       netsnmp_iterator_info *mydata)
{
    return NULL;
#if 0
    netsnmp_variable_list *vptr;

    *my_loop_context = /* XXX */ ;
    *my_data_context = /* XXX */ ;

    vptr = put_index_data;

    snmp_set_var_value(vptr,
                       (u_char *) /* XXX: alMatrixTopNControlIndex data */
                       , /* XXX: length of alMatrixTopNControlIndex data */
                       );
    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *) /* XXX: alMatrixTopNIndex data */ ,
                       /* XXX: length of alMatrixTopNIndex data */ );
    vptr = vptr->next_variable;

    return put_index_data;
#endif
}


/** functionally the same as alMatrixTopNTable_get_first_data_point, but
   my_loop_context has already been set to a previous value and should
   be updated to the next in the list.  For example, if it was a
   linked list, you might want to cast it and the return
   my_loop_context->next.  The my_data_context pointer should be set
   to something you need later and the indexes in put_index_data
   updated again. */

netsnmp_variable_list *
alMatrixTopNTable_get_next_data_point(void **my_loop_context,
                                      void **my_data_context,
                                      netsnmp_variable_list *put_index_data,
                                      netsnmp_iterator_info *mydata)
{
    return NULL;
#if 0
    netsnmp_variable_list *vptr;

    *my_loop_context = /* XXX */ ;
    *my_data_context = /* XXX */ ;

    vptr = put_index_data;

    snmp_set_var_value(vptr,
                       (u_char *) /* XXX: alMatrixTopNControlIndex data */
                       , /* XXX: length of alMatrixTopNControlIndex data */
                       );
    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *) /* XXX: alMatrixTopNIndex data */ ,
                       /* XXX: length of alMatrixTopNIndex data */ );
    vptr = vptr->next_variable;

    return put_index_data;
#endif
}


/** handles requests for the alMatrixTopNTable table, if anything else needs to be done */
int
alMatrixTopNTable_handler(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info *reqinfo,
                          netsnmp_request_info *requests)
{
#if 0
    netsnmp_request_info	*request;
    netsnmp_table_request_info	*table_info;
    netsnmp_variable_list	*var;

    for (request = requests; request; request = request->next) {
        var = request->requestvb;
        if (request->processed != 0)
            continue;

        /*
         * perform anything here that you need to do before each
         * request is processed.
         */

        /*
         * the following extracts the my_data_context pointer set in
         * the loop functions above.  You can then use the results to
         * help return data for the columns of the alMatrixTopNTable table in question
         */
        /*
         * XXX
         */  = ( /* XXX */ *)netsnmp_extract_iterator_context(request);
        if ( /* XXX */  == NULL) {
            if (reqinfo->mode == MODE_GET) {
                netsnmp_set_request_error(reqinfo, request,
                                          SNMP_NOSUCHINSTANCE);
                continue;
            }
            /*
             * XXX: no row existed, if you support creation and this is a
             * set, start dealing with it here, else continue
             */
        }

        /*
         * extracts the information about the table from the request
         */
        table_info = netsnmp_extract_table_info(request);
        /*
         * table_info->colnum contains the column number requested
         */
        /*
         * table_info->indexes contains a linked list of snmp variable
         * bindings for the indexes of the table.  Values in the list
         * have been set corresponding to the indexes of the
         * request
         */
        if (table_info == NULL) {
            continue;
        }

        switch (reqinfo->mode) {
            /*
             * the table_iterator helper should change all GETNEXTs
             * into GETs for you automatically, so you don't have to
             * worry about the GETNEXT case.  Only GETs and SETs need
             * to be dealt with here
             */
        case MODE_GET:
            switch (table_info->colnum) {
            case COLUMN_ALMATRIXTOPNPROTOCOLDIRLOCALINDEX:
                snmp_set_var_typed_value(var, ASN_INTEGER,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNSOURCEADDRESS:
                snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNDESTADDRESS:
                snmp_set_var_typed_value(var, ASN_OCTET_STR,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNAPPPROTOCOLDIRLOCALINDEX:
                snmp_set_var_typed_value(var, ASN_INTEGER,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNPKTRATE:
                snmp_set_var_typed_value(var, ASN_GAUGE,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNREVERSEPKTRATE:
                snmp_set_var_typed_value(var, ASN_GAUGE,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNOCTETRATE:
                snmp_set_var_typed_value(var, ASN_GAUGE,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            case COLUMN_ALMATRIXTOPNREVERSEOCTETRATE:
                snmp_set_var_typed_value(var, ASN_GAUGE,
                                         (u_char *) /* XXX: column data */
                                         , /* XXX: column data length */ );
                break;

            default:
                /*
                 * We shouldn't get here
                 */
                snmp_log(LOG_ERR,
                         "problem encountered in alMatrixTopNTable_handler: unknown column\n");
            }
            break;

        case MODE_SET_RESERVE1:
            /*
             * set handling...
             */

        default:
            snmp_log(LOG_ERR,
                     "problem encountered in alMatrixTopNTable_handler: unsupported mode\n");
        }
    }
#endif
    return SNMP_ERR_NOERROR;
}


/** returns the first data point within the alMatrixDSTable table data.

    Set the my_loop_context variable to the first data point structure
    of your choice (from which you can find the next one).  This could
    be anything from the first node in a linked list, to an integer
    pointer containing the beginning of an array variable.

    Set the my_data_context variable to something to be returned to
    you later that will provide you with the data to return in a given
    row.  This could be the same pointer as what my_loop_context is
    set to, or something different.

    The put_index_data variable contains a list of snmp variable
    bindings, one for each index in your table.  Set the values of
    each appropriately according to the data matching the first row
    and return the put_index_data variable at the end of the function.
*/
netsnmp_variable_list *
alMatrixDSTable_get_first_data_point(void **my_loop_context,
                                     void **my_data_context,
                                     netsnmp_variable_list *put_index_data,
                                     netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    uint32_t		    indice;
    uint32_t		    tripa[6];

    if (almatrix_ds_tabela_prepara(&indice) != SUCCESS) {
	return NULL;
    }

    if (almatrix_ds_helper(indice, &tripa[0], &tripa[1], &tripa[2],
		&tripa[3], &tripa[4], &tripa[5]) != SUCCESS) {
	return NULL;
    }

    *my_loop_context = (void *)indice;
    *my_data_context = (void *)indice;

    vptr = put_index_data;

    snmp_set_var_value(vptr, (u_char *)&tripa[0], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[1], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[2], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[3], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[4], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[5], sizeof(uint32_t));

    vptr = vptr->next_variable;

    return put_index_data;
}


/** functionally the same as alMatrixDSTable_get_first_data_point, but
   my_loop_context has already been set to a previous value and should
   be updated to the next in the list.  For example, if it was a
   linked list, you might want to cast it and the return
   my_loop_context->next.  The my_data_context pointer should be set
   to something you need later and the indexes in put_index_data
   updated again. */

netsnmp_variable_list *
alMatrixDSTable_get_next_data_point(void **my_loop_context,
                                    void **my_data_context,
                                    netsnmp_variable_list *put_index_data,
                                    netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    uint32_t		    indice;
    uint32_t		    tripa[6];

    if (almatrix_ds_tabela_proximo(&indice) != SUCCESS) {
	return NULL;
    }

    if (almatrix_ds_helper(indice, &tripa[0], &tripa[1], &tripa[2],
		&tripa[3], &tripa[4], &tripa[5]) != SUCCESS) {
	return NULL;
    }

    *my_loop_context = (void *)indice;
    *my_data_context = (void *)indice;

    vptr = put_index_data;

    snmp_set_var_value(vptr, (u_char *)&tripa[0], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[1], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[2], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[3], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[4], sizeof(uint32_t));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&tripa[5], sizeof(uint32_t));

    vptr = vptr->next_variable;

    return put_index_data;
}


/** handles requests for the alMatrixDSTable table, if anything else needs to be done */
int
alMatrixDSTable_handler(netsnmp_mib_handler *handler,
                        netsnmp_handler_registration *reginfo,
                        netsnmp_agent_request_info *reqinfo,
                        netsnmp_request_info *requests)
{
    netsnmp_request_info	*request;
    netsnmp_table_request_info	*table_info;
    netsnmp_variable_list	*var;
    uint32_t			indice;
    uint32_t			valor;

    for (request = requests; request; request = request->next) {
        var = request->requestvb;
        if (request->processed != 0)
            continue;

        /*
         * perform anything here that you need to do before each
         * request is processed.
         */

        /*
         * the following extracts the my_data_context pointer set in
         * the loop functions above.  You can then use the results to
         * help return data for the columns of the alMatrixDSTable table in question
         */

	indice = (uint32_t)netsnmp_extract_iterator_context(request);
        if (almatrix_ds_testa(indice) != SUCCESS) {
            if (reqinfo->mode == MODE_GET) {
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                continue;
            }
            /*
             * XXX: no row existed, if you support creation and this is a
             * set, start dealing with it here, else continue
             */

	    netsnmp_set_request_error(reqinfo, request, SNMP_ERR_NOCREATION);
	    return SNMP_ERR_NOCREATION;
        }

        /*
         * extracts the information about the table from the request
         */
        table_info = netsnmp_extract_table_info(request);
        /*
         * table_info->colnum contains the column number requested
         */
        /*
         * table_info->indexes contains a linked list of snmp variable
         * bindings for the indexes of the table.  Values in the list
         * have been set corresponding to the indexes of the
         * request
         */
        if (table_info == NULL) {
            continue;
        }

        switch (reqinfo->mode) {
            /*
             * the table_iterator helper should change all GETNEXTs
             * into GETs for you automatically, so you don't have to
             * worry about the GETNEXT case.  Only GETs and SETs need
             * to be dealt with here
             */
        case MODE_GET:
            switch (table_info->colnum) {
            case COLUMN_ALMATRIXDSPKTS:
		if (almatrix_ds_busca_pkts(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_GAUGE, (u_char *)&valor, sizeof(valor));
                break;

            case COLUMN_ALMATRIXDSOCTETS:
		if (almatrix_ds_busca_octets(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_GAUGE, (u_char *)&valor, sizeof(valor));
                break;

            case COLUMN_ALMATRIXDSCREATETIME:
		if (almatrix_ds_busca_createtime(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_TIMETICKS, (u_char *)&valor, sizeof(valor));
                break;

            default:
                /*
                 * We shouldn't get here
                 */
                snmp_log(LOG_ERR,
                         "problem encountered in alMatrixDSTable_handler: unknown column\n");
            }
            break;

        case MODE_SET_RESERVE1:
            /*
             * set handling...
             */

        default:
            snmp_log(LOG_ERR,
                     "problem encountered in alMatrixDSTable_handler: unsupported mode\n");
        }
    }
    return SNMP_ERR_NOERROR;
}

