/*
 * Ramon - A RMON2 Network Monitoring Agent
 * Copyright (C) 2003 Ricardo Nabinger Sanchez
 *
 * This file is part of Ramon, a network monitoring agent which implements
 * the MIB proposed in RFC-2021.
 *
 * Ramon is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
 *
 * Ramon is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with program; see the file COPYING. If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "nlHost.h"

/* needed stuff to access tables */
#include "hlhost.h"
#include "nlhost.h"
#include "exit_codes.h"


/** Initialize the hlHostControlTable table by defining its contents and how it's structured */
void
initialize_table_hlHostControlTable(void)
{
    static oid hlHostControlTable_oid[] = { 1, 3, 6, 1, 2, 1, 16, 14, 1 };
    netsnmp_table_registration_info *table_info;
    netsnmp_handler_registration    *my_handler;
    netsnmp_iterator_info	    *iinfo;

    /*
     * create the table structure itself
     */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);

    /*
     * if your table is read only, it's easiest to change the
     * HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY
     */
    my_handler = netsnmp_create_handler_registration("hlHostControlTable",
                                                     hlHostControlTable_handler,
                                                     hlHostControlTable_oid,
                                                     OID_LENGTH(hlHostControlTable_oid),
                                                     HANDLER_CAN_RWRITE);

    if (!my_handler || !table_info || !iinfo)
        return;                 /* mallocs failed */

    /***************************************************
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: hlHostControlIndex */
                                     0);

    table_info->min_column = 2;
    table_info->max_column = 12;

    /*
     * iterator access routines
     */
    iinfo->get_first_data_point = hlHostControlTable_get_first_data_point;
    iinfo->get_next_data_point = hlHostControlTable_get_next_data_point;

    iinfo->table_reginfo = table_info;

    /***************************************************
     * registering the table with the master agent
     */
    DEBUGMSGTL(("initialize_table_hlHostControlTable",
                "Registering table hlHostControlTable as a table iterator\n"));
    netsnmp_register_table_iterator(my_handler, iinfo);

    snmp_log(LOG_INFO, "success: hlHost initialized\n");
}


/** Initialize the nlHostTable table by defining its contents and how it's structured */
void
initialize_table_nlHostTable(void)
{
    static oid nlHostTable_oid[] = { 1, 3, 6, 1, 2, 1, 16, 14, 2 };
    netsnmp_table_registration_info *table_info;
    netsnmp_handler_registration    *my_handler;
    netsnmp_iterator_info	    *iinfo;

    /*
     * create the table structure itself
     */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);

    /*
     * if your table is read only, it's easiest to change the
     * HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY
     */
    my_handler = netsnmp_create_handler_registration("nlHostTable",
                                                     nlHostTable_handler,
                                                     nlHostTable_oid,
                                                     OID_LENGTH(nlHostTable_oid),
                                                     HANDLER_CAN_RONLY);

    if (!my_handler || !table_info || !iinfo)
        return;                 /* mallocs failed */

    /***************************************************
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(table_info, ASN_INTEGER,   /* index: hlHostControlIndex */
                                     ASN_TIMETICKS,     /* index: nlHostTimeMark */
                                     ASN_INTEGER,       /* index: protocolDirLocalIndex */
                                     ASN_OCTET_STR,     /* index: nlHostAddress */
                                     0);

    table_info->min_column = 3;
    table_info->max_column = 8;

    /*
     * iterator access routines
     */
    iinfo->get_first_data_point = nlHostTable_get_first_data_point;
    iinfo->get_next_data_point = nlHostTable_get_next_data_point;

    iinfo->table_reginfo = table_info;

    /***************************************************
     * registering the table with the master agent
     */
    DEBUGMSGTL(("initialize_table_nlHostTable",
                "Registering table nlHostTable as a table iterator\n"));
    netsnmp_register_table_iterator(my_handler, iinfo);

    snmp_log(LOG_INFO, "success: nlHost initialized\n");
}


/** Initializes the nlHost module */
void
init_nlHost(void)
{

    /*
     * here we initialize all the tables we're planning on supporting
     */
    initialize_table_hlHostControlTable();
    initialize_table_nlHostTable();
}


/** returns the first data point within the hlHostControlTable table data.

    Set the my_loop_context variable to the first data point structure
    of your choice (from which you can find the next one).  This could
    be anything from the first node in a linked list, to an integer
    pointer containing the beginning of an array variable.

    Set the my_data_context variable to something to be returned to
    you later that will provide you with the data to return in a given
    row.  This could be the same pointer as what my_loop_context is
    set to, or something different.

    The put_index_data variable contains a list of snmp variable
    bindings, one for each index in your table.  Set the values of
    each appropriately according to the data matching the first row
    and return the put_index_data variable at the end of the function.
*/
netsnmp_variable_list *
hlHostControlTable_get_first_data_point(void **my_loop_context,
                                        void **my_data_context,
                                        netsnmp_variable_list *put_index_data,
                                        netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    uint32_t		    indice;

    if (hlhost_tabela_prepara(&indice) != SUCCESS) {
	/* hmm, no entries? */
	return NULL;
    }

    *my_loop_context = (void *)indice;
    *my_data_context = (void *)indice;

    vptr = put_index_data;

    snmp_set_var_value(vptr, (u_char *)&indice, sizeof(indice));
    vptr = vptr->next_variable;

    return put_index_data;
}


/** functionally the same as hlHostControlTable_get_first_data_point, but
   my_loop_context has already been set to a previous value and should
   be updated to the next in the list.  For example, if it was a
   linked list, you might want to cast it and the return
   my_loop_context->next.  The my_data_context pointer should be set
   to something you need later and the indexes in put_index_data
   updated again. */

netsnmp_variable_list *
hlHostControlTable_get_next_data_point(void **my_loop_context,
                                       void **my_data_context,
                                       netsnmp_variable_list *put_index_data,
                                       netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    uint32_t		    indice;

    if (hlhost_tabela_proximo(&indice) != SUCCESS) {
	/* no more entries */
	return NULL;
    }

    *my_loop_context = (void *)indice;
    *my_data_context = (void *)indice;

    vptr = put_index_data;

    snmp_set_var_value(vptr, (u_char *)&indice, sizeof(indice));
    vptr = vptr->next_variable;

    return put_index_data;
}


/** handles requests for the hlHostControlTable table, if anything else needs to be done */
int
hlHostControlTable_handler(netsnmp_mib_handler *handler,
                           netsnmp_handler_registration *reginfo,
                           netsnmp_agent_request_info *reqinfo,
                           netsnmp_request_info *requests)
{
    /* IF-MIB::ifIndex.n == .1.3.6.1.2.1.2.2.1.1.n */
    char			buffer[64];
    oid                         ifindex_oid[] = {1, 3, 6, 1, 2, 1, 2, 2, 1, 1, 0};
    netsnmp_request_info	*request;
    netsnmp_table_request_info	*table_info;
    netsnmp_variable_list	*var;
    uint32_t			valor_u32;
    unsigned int		indice;
    int				valor_s;
    char			*owner_ptr;

    for (request = requests; request; request = request->next) {
        var = request->requestvb;
        if (request->processed != 0)
            continue;

        /*
         * perform anything here that you need to do before each
         * request is processed.
         */

        /*
         * the following extracts the my_data_context pointer set in
         * the loop functions above.  You can then use the results to
         * help return data for the columns of the hlHostControlTable table in question
         */
        /*
         * XXX
         */
	indice = (uint32_t)netsnmp_extract_iterator_context(request);
        if (hlhost_tabela_testa(indice) != SUCCESS) {
            if (reqinfo->mode == MODE_GET) {
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                continue;
            }
            /*
             * XXX: no row existed, if you support creation and this is a
             * set, start dealing with it here, else continue
             */
        }

	ifindex_oid[10] = (oid)indice;

        /*
         * extracts the information about the table from the request
         */
        table_info = netsnmp_extract_table_info(request);
        /*
         * table_info->colnum contains the column number requested
         */
        /*
         * table_info->indexes contains a linked list of snmp variable
         * bindings for the indexes of the table.  Values in the list
         * have been set corresponding to the indexes of the
         * request
         */
        if (table_info == NULL) {
            continue;
        }

        switch (reqinfo->mode) {
            /*
             * the table_iterator helper should change all GETNEXTs
             * into GETs for you automatically, so you don't have to
             * worry about the GETNEXT case.  Only GETs and SETs need
             * to be dealt with here
             */
        case MODE_GET:
            switch (table_info->colnum) {
            case COLUMN_HLHOSTCONTROLDATASOURCE:
                snmp_set_var_typed_value(var, ASN_OBJECT_ID, (u_char *)ifindex_oid, sizeof(ifindex_oid));
                break;

            case COLUMN_HLHOSTCONTROLNLDROPPEDFRAMES:
		if (hlhost_getNlDroppedFrames(indice, &valor_u32) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_COUNTER, (u_char *)&valor_u32, sizeof(valor_u32));
                break;

            case COLUMN_HLHOSTCONTROLNLINSERTS:
       		if (hlhost_getNlInserts(indice, &valor_u32) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
		snmp_set_var_typed_value(var, ASN_COUNTER, (u_char *)&valor_u32, sizeof(valor_u32));
                break;

            case COLUMN_HLHOSTCONTROLNLDELETES:
       		if (hlhost_getNlDeletes(indice, &valor_u32) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
		snmp_set_var_typed_value(var, ASN_COUNTER, (u_char *)&valor_u32, sizeof(valor_u32));
                break;

            case COLUMN_HLHOSTCONTROLNLMAXDESIREDENTRIES:
       		if (hlhost_getNlMaxentries(indice, &valor_s) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_INTEGER, (u_char *)&valor_s, sizeof(valor_s));
                break;

            case COLUMN_HLHOSTCONTROLALDROPPEDFRAMES:
       		if (hlhost_getAlDroppedFrames(indice, &valor_u32) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_COUNTER, (u_char *)&valor_u32, sizeof(valor_u32));
                break;

            case COLUMN_HLHOSTCONTROLALINSERTS:
       		if (hlhost_getAlInserts(indice, &valor_u32) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_COUNTER, (u_char *)&valor_u32, sizeof(valor_u32));
                break;

            case COLUMN_HLHOSTCONTROLALDELETES:
       		if (hlhost_getAlDeletes(indice, &valor_u32) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_COUNTER, (u_char *)&valor_u32, sizeof(valor_u32));
                break;

            case COLUMN_HLHOSTCONTROLALMAXDESIREDENTRIES:
       		if (hlhost_getAlMaxentries(indice, &valor_s) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_INTEGER, (u_char *)&valor_s, sizeof(valor_s));
                break;

            case COLUMN_HLHOSTCONTROLOWNER:
		valor_s = hlhost_busca_owner(indice, buffer, sizeof(buffer));
		if (valor_s > 0) {
		    snmp_set_var_typed_value(var, ASN_OCTET_STR, (u_char *)owner_ptr,
			    valor_u32);
		}
		else {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                break;

            case COLUMN_HLHOSTCONTROLSTATUS:
		valor_s = hlhost_getRowstatus(indice);
		if (valor_s < 0) {
       		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_INTEGER, (u_char *)&valor_s, sizeof(valor_s));
                break;

            default:
                /*
                 * We shouldn't get here
                 */
                snmp_log(LOG_ERR,
                         "problem encountered in hlHostControlTable_handler: unknown column\n");
            }
            break;

        case MODE_SET_RESERVE1:
            /*
             * set handling...
             */

        default:
            snmp_log(LOG_ERR,
                     "problem encountered in hlHostControlTable_handler: unsupported mode\n");
        }
    }
    return SNMP_ERR_NOERROR;
}


/** returns the first data point within the nlHostTable table data.

    Set the my_loop_context variable to the first data point structure
    of your choice (from which you can find the next one).  This could
    be anything from the first node in a linked list, to an integer
    pointer containing the beginning of an array variable.

    Set the my_data_context variable to something to be returned to
    you later that will provide you with the data to return in a given
    row.  This could be the same pointer as what my_loop_context is
    set to, or something different.

    The put_index_data variable contains a list of snmp variable
    bindings, one for each index in your table.  Set the values of
    each appropriately according to the data matching the first row
    and return the put_index_data variable at the end of the function.
*/
netsnmp_variable_list *
nlHostTable_get_first_data_point(void **my_loop_context,
                                 void **my_data_context,
                                 netsnmp_variable_list *put_index_data,
                                 netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    uint32_t		    indice;
    uint32_t		    hlhost_control_index;
    uint32_t		    nlhost_timemark;
    uint32_t		    pdir_localindex;
    uint32_t		    nlhost_address;

    if (nlhost_tabela_prepara(&indice) != SUCCESS) {
	/* error or no elements */
	return NULL;
    }

    if (nlhost_helper(indice, &hlhost_control_index, &nlhost_timemark,
		&pdir_localindex, &nlhost_address) != SUCCESS) {
	return NULL;
    }

    *my_loop_context = (void *)indice;
    *my_data_context = (void *)indice;

    vptr = put_index_data;

    /* hlHostControlIndex data */
    snmp_set_var_value(vptr, (u_char *)&hlhost_control_index,
	    sizeof(hlhost_control_index));
    vptr = vptr->next_variable;

    /* nlHostTimeMark data */
    snmp_set_var_value(vptr, (u_char *)&nlhost_timemark,
	    sizeof(nlhost_timemark));
    vptr = vptr->next_variable;

    /* protocolDirLocalIndex data */
    snmp_set_var_value(vptr, (u_char *)&pdir_localindex,
	    sizeof(pdir_localindex));
    vptr = vptr->next_variable;

    /* nlHostAddress data */
    snmp_set_var_value(vptr, (u_char *)&nlhost_address,
	    sizeof(nlhost_address));
    vptr = vptr->next_variable;

    return put_index_data;
}


/** functionally the same as nlHostTable_get_first_data_point, but
   my_loop_context has already been set to a previous value and should
   be updated to the next in the list.  For example, if it was a
   linked list, you might want to cast it and the return
   my_loop_context->next.  The my_data_context pointer should be set
   to something you need later and the indexes in put_index_data
   updated again. */

netsnmp_variable_list *
nlHostTable_get_next_data_point(void **my_loop_context,
                                void **my_data_context,
                                netsnmp_variable_list *put_index_data,
                                netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    uint32_t		    indice;
    uint32_t		    hlhost_control_index;
    uint32_t		    nlhost_timemark;
    uint32_t		    pdir_localindex;
    uint32_t		    nlhost_address;

    if (nlhost_tabela_proximo(&indice) != SUCCESS) {
	/* error or no elements */
	return NULL;
    }

    if (nlhost_helper(indice, &hlhost_control_index, &nlhost_timemark,
		&pdir_localindex, &nlhost_address) != SUCCESS) {
	return NULL;
    }

    *my_loop_context = (void *)indice;
    *my_data_context = (void *)indice;

    vptr = put_index_data;

    /* hlHostControlIndex data */
    snmp_set_var_value(vptr, (u_char *)&hlhost_control_index,
	    sizeof(hlhost_control_index));
    vptr = vptr->next_variable;

    /* nlHostTimeMark data */
    snmp_set_var_value(vptr, (u_char *)&nlhost_timemark,
	    sizeof(nlhost_timemark));
    vptr = vptr->next_variable;

    /* protocolDirLocalIndex data */
    snmp_set_var_value(vptr, (u_char *)&pdir_localindex,
	    sizeof(pdir_localindex));
    vptr = vptr->next_variable;

    /* nlHostAddress data */
    snmp_set_var_value(vptr, (u_char *)&nlhost_address,
	    sizeof(nlhost_address));
    vptr = vptr->next_variable;

    return put_index_data;
}


/** handles requests for the nlHostTable table, if anything else needs to be done */
int
nlHostTable_handler(netsnmp_mib_handler *handler,
                    netsnmp_handler_registration *reginfo,
                    netsnmp_agent_request_info *reqinfo,
                    netsnmp_request_info *requests)
{
    netsnmp_request_info	*request;
    netsnmp_table_request_info	*table_info;
    netsnmp_variable_list	*var;
    uint32_t			indice;
    uint32_t			valor;

    for (request = requests; request; request = request->next) {
        var = request->requestvb;
        if (request->processed != 0)
            continue;

        /*
         * perform anything here that you need to do before each
         * request is processed.
         */

        /*
         * the following extracts the my_data_context pointer set in
         * the loop functions above.  You can then use the results to
         * help return data for the columns of the nlHostTable table in question
         */

	indice = (uint32_t)netsnmp_extract_iterator_context(request);
        if (nlhost_tabela_testa(indice) != SUCCESS) {
            if (reqinfo->mode == MODE_GET) {
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                continue;
            }
            /*
             * XXX: no row existed, if you support creation and this is a
             * set, start dealing with it here, else continue
             */

	    netsnmp_set_request_error(reqinfo, request, SNMP_ERR_NOCREATION);
	    return SNMP_ERR_NOCREATION;
        }

        /*
         * extracts the information about the table from the request
         */
        table_info = netsnmp_extract_table_info(request);
        /*
         * table_info->colnum contains the column number requested
         */
        /*
         * table_info->indexes contains a linked list of snmp variable
         * bindings for the indexes of the table.  Values in the list
         * have been set corresponding to the indexes of the
         * request
         */
        if (table_info == NULL) {
            continue;
        }

        switch (reqinfo->mode) {
            /*
             * the table_iterator helper should change all GETNEXTs
             * into GETs for you automatically, so you don't have to
             * worry about the GETNEXT case.  Only GETs and SETs need
             * to be dealt with here
             */
        case MODE_GET:
            switch (table_info->colnum) {
            case COLUMN_NLHOSTINPKTS:
		if (nlhost_busca_inpkts(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_GAUGE, (u_char *)&valor, sizeof(valor));
                break;

            case COLUMN_NLHOSTOUTPKTS:
       		if (nlhost_busca_outpkts(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
		snmp_set_var_typed_value(var, ASN_GAUGE, (u_char *)&valor, sizeof(valor));
                break;

            case COLUMN_NLHOSTINOCTETS:
       		if (nlhost_busca_inoctets(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
		snmp_set_var_typed_value(var, ASN_GAUGE, (u_char *)&valor, sizeof(valor));
                break;

            case COLUMN_NLHOSTOUTOCTETS:
		if (nlhost_busca_outoctets(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
                snmp_set_var_typed_value(var, ASN_GAUGE, (u_char *)&valor, sizeof(valor));
                break;

            case COLUMN_NLHOSTOUTMACNONUNICASTPKTS:
       		if (nlhost_busca_outmacnonunicast(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
		snmp_set_var_typed_value(var, ASN_GAUGE, (u_char *)&valor, sizeof(valor));
                break;

            case COLUMN_NLHOSTCREATETIME:
       		if (nlhost_busca_createtime(indice, &valor) != SUCCESS) {
		    netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
		    return SNMP_ERR_NOSUCHNAME;
		}
		snmp_set_var_typed_value(var, ASN_TIMETICKS, (u_char *)&valor, sizeof(valor));
                break;

            default:
                /*
                 * We shouldn't get here
                 */
                snmp_log(LOG_ERR,
                         "problem encountered in nlHostTable_handler: unknown column\n");
            }
            break;

        case MODE_SET_RESERVE1:
            /*
             * set handling...
             */

        default:
            snmp_log(LOG_ERR,
                     "problem encountered in nlHostTable_handler: unsupported mode\n");
        }
    }
    return SNMP_ERR_NOERROR;
}

