/*
 * Ramon - A RMON2 Network Monitoring Agent
 * Copyright (C) 2003 Ricardo Nabinger Sanchez
 *
 * This file is part of Ramon, a network monitoring agent which implements
 * the MIB proposed in RFC-2021.
 *
 * Ramon is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
 *
 * Ramon is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with program; see the file COPYING. If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "protocolDist.h"

#include <pthread.h>
#include "protocoldist.h"
#include "conversor.h"
#include "exit_codes.h"


static pthread_t   thr_captura;


/** Initialize the protocolDistStatsTable table by defining its contents and how it's structured */
void
initialize_table_protocolDistStatsTable(void)
{
    static oid protocolDistStatsTable_oid[] = { 1, 3, 6, 1, 2, 1, 16, 12, 2 };
    netsnmp_table_registration_info *table_info;
    netsnmp_handler_registration    *my_handler;
    netsnmp_iterator_info	    *iinfo;

    /*
     * create the table structure itself
     */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);

    /*
     * if your table is read only, it's easiest to change the
     * HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY
     */
    my_handler =
        netsnmp_create_handler_registration("protocolDistStatsTable",
                                            protocolDistStatsTable_handler,
                                            protocolDistStatsTable_oid,
                                            OID_LENGTH(protocolDistStatsTable_oid),
                                            HANDLER_CAN_RONLY);

    if (!my_handler || !table_info || !iinfo) {
        return;                 /* mallocs failed */
    }

    /***************************************************
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(table_info,
				     ASN_INTEGER,   /* index: protocolDistControlIndex */
                                     ASN_INTEGER,   /* index: protocolDirLocalIndex */
                                     0);

    table_info->min_column = 1;
    table_info->max_column = 2;

    /*
     * iterator access routines
     */
    iinfo->get_first_data_point = protocolDistStatsTable_get_first_data_point;
    iinfo->get_next_data_point = protocolDistStatsTable_get_next_data_point;

    iinfo->table_reginfo = table_info;

    /***************************************************
     * registering the table with the master agent
     */
    DEBUGMSGTL(("initialize_table_protocolDistStatsTable",
                "Registering table protocolDistStatsTable as a table iterator\n"));
    netsnmp_register_table_iterator(my_handler, iinfo);
}


/** Initialize the protocolDistControlTable table by defining its contents and how it's structured */
void
initialize_table_protocolDistControlTable(void)
{
    static oid protocolDistControlTable_oid[] = { 1, 3, 6, 1, 2, 1, 16, 12, 1 };
    netsnmp_table_registration_info *table_info;
    netsnmp_handler_registration    *my_handler;
    netsnmp_iterator_info	    *iinfo;

    /*
     * create the table structure itself
     */
    table_info = SNMP_MALLOC_TYPEDEF(netsnmp_table_registration_info);
    iinfo = SNMP_MALLOC_TYPEDEF(netsnmp_iterator_info);

    /*
     * if your table is read only, it's easiest to change the
     * HANDLER_CAN_RWRITE definition below to HANDLER_CAN_RONLY
     */
    my_handler =
        netsnmp_create_handler_registration("protocolDistControlTable",
                                            protocolDistControlTable_handler,
                                            protocolDistControlTable_oid,
                                            OID_LENGTH(protocolDistControlTable_oid),
                                            HANDLER_CAN_RWRITE);

    if (!my_handler || !table_info || !iinfo)
        return;                 /* mallocs failed */

    /***************************************************
     * Setting up the table's definition
     */
    netsnmp_table_helper_add_indexes(table_info,
				     ASN_INTEGER,   /* index: protocolDistControlIndex */
                                     0);

    table_info->min_column = 2;
    table_info->max_column = 6;

    /*
     * iterator access routines
     */
    iinfo->get_first_data_point = protocolDistControlTable_get_first_data_point;
    iinfo->get_next_data_point = protocolDistControlTable_get_next_data_point;

    iinfo->table_reginfo = table_info;

    /***************************************************
     * registering the table with the master agent
     */
    DEBUGMSGTL(("initialize_table_protocolDistControlTable",
                "Registering table protocolDistControlTable as a table iterator\n"));
    netsnmp_register_table_iterator(my_handler, iinfo);
}

/** Initializes the protocolDist module */
void
init_protocolDist(void)
{

    /*
     * here we initialize all the tables we're planning on supporting
     */
    initialize_table_protocolDistStatsTable();
    initialize_table_protocolDistControlTable();

    if (conv_inicializa() == SUCCESS) {
	if (pthread_create(&thr_captura, NULL, captura_processa_pacote, NULL) != 0) {
	    /* panic time! */
	    snmp_log(LOG_ERR, " *** protocolDist: could not create thread\n");
	    return;
	}
	snmp_log(LOG_INFO, "success: protocolDist initialized\n");
    }
    else {
	snmp_log(LOG_ERR, " *** protocolDist: initialization error\n");
    }
}

/** returns the first data point within the protocolDistStatsTable table data.

    Set the my_loop_context variable to the first data point structure
    of your choice (from which you can find the next one).  This could
    be anything from the first node in a linked list, to an integer
    pointer containing the beginning of an array variable.

    Set the my_data_context variable to something to be returned to
    you later that will provide you with the data to return in a given
    row.  This could be the same pointer as what my_loop_context is
    set to, or something different.

    The put_index_data variable contains a list of snmp variable
    bindings, one for each index in your table.  Set the values of
    each appropriately according to the data matching the first row
    and return the put_index_data variable at the end of the function.
*/
netsnmp_variable_list *
protocolDistStatsTable_get_first_data_point(void **my_loop_context,
                                            void **my_data_context,
                                            netsnmp_variable_list *put_index_data,
                                            netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    uint32_t		    indice;
    uint32_t		    indice_control;
    uint32_t		    indice_pdir;

//    /* ordenar o conjunto de dados */
//    if (pdist_stats_tabela_prepara() != SUCCESS) {
//	/* algo saiu errado ou não há elementos */
//	return NULL;
//    }

    /* tudo pronto: solicitar o primeiro elemento */
    if (pdist_stats_tabela_primeiro(&indice) != SUCCESS) {
	/* algo saiu errado */
	return NULL;
    }

    /* pegar os indices */
    if ((pdist_stats_tabela_busca_controlindex(indice, &indice_control) != SUCCESS) ||
	    (pdist_stats_tabela_busca_protdirindex(indice, &indice_pdir) != SUCCESS)) {
	return NULL;
    }

    *my_loop_context = (void *)indice;
    *my_data_context = (void *)indice;

    vptr = put_index_data;
    snmp_set_var_value(vptr, (u_char *)&indice_control, sizeof(indice_control));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&indice_pdir, sizeof(indice_pdir));
    vptr = vptr->next_variable;

    return put_index_data;
}


/** functionally the same as protocolDistStatsTable_get_first_data_point, but
   my_loop_context has already been set to a previous value and should
   be updated to the next in the list.  For example, if it was a
   linked list, you might want to cast it and the return
   my_loop_context->next.  The my_data_context pointer should be set
   to something you need later and the indexes in put_index_data
   updated again. */

netsnmp_variable_list *
protocolDistStatsTable_get_next_data_point(void **my_loop_context,
                                           void **my_data_context,
                                           netsnmp_variable_list *put_index_data,
                                           netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    uint32_t		    indice;
    uint32_t		    indice_control;
    uint32_t		    indice_pdir;

    /* solicitar o proximo elemento */
    if (pdist_stats_tabela_prox(&indice) != SUCCESS) {
	/* algo saiu errado */
	return NULL;
    }

    /* pegar os indices */
    if ((pdist_stats_tabela_busca_controlindex(indice, &indice_control) != SUCCESS) ||
	    (pdist_stats_tabela_busca_protdirindex(indice, &indice_pdir) != SUCCESS)) {
	return NULL;
    }

    *my_loop_context = (void *)indice;
    *my_data_context = (void *)indice;

    vptr = put_index_data;
    snmp_set_var_value(vptr, (u_char *)&indice_control, sizeof(indice_control));

    vptr = vptr->next_variable;
    snmp_set_var_value(vptr, (u_char *)&indice_pdir, sizeof(indice_pdir));
    vptr = vptr->next_variable;

    return put_index_data;
}


/** handles requests for the protocolDistStatsTable table, if anything else needs to be done */
int
protocolDistStatsTable_handler(netsnmp_mib_handler *handler,
                               netsnmp_handler_registration *reginfo,
                               netsnmp_agent_request_info *reqinfo,
                               netsnmp_request_info *requests)
{
    netsnmp_request_info	*request;
    netsnmp_table_request_info	*table_info;
    netsnmp_variable_list	*var;

    uint32_t			indice;
    uint32_t			valor;

    for (request = requests; request; request = request->next) {
        var = request->requestvb;
        if (request->processed != 0) {
            continue;
	}

        /*
         * perform anything here that you need to do before each
         * request is processed.
         */

        /*
         * the following extracts the my_data_context pointer set in
         * the loop functions above.  You can then use the results to
         * help return data for the columns of the protocolDistStatsTable table in question
         */
	indice = (uint32_t)netsnmp_extract_iterator_context(request);
	if (pdist_stats_tabela_testa(indice) != SUCCESS) {
            if (reqinfo->mode == MODE_GET) {
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                continue;
            }
            /*
             * XXX: no row existed, if you support creation and this is a
             * set, start dealing with it here, else continue
             */
        }

        /*
         * extracts the information about the table from the request
         */
        table_info = netsnmp_extract_table_info(request);
        /*
         * table_info->colnum contains the column number requested
         */
        /*
         * table_info->indexes contains a linked list of snmp variable
         * bindings for the indexes of the table.  Values in the list
         * have been set corresponding to the indexes of the
         * request
         */
        if (table_info == NULL) {
            continue;
        }

        switch (reqinfo->mode) {
            /*
             * the table_iterator helper should change all GETNEXTs
             * into GETs for you automatically, so you don't have to
             * worry about the GETNEXT case.  Only GETs and SETs need
             * to be dealt with here
             */
        case MODE_GET:
            switch (table_info->colnum) {
		case COLUMN_PROTOCOLDISTSTATSPKTS:
		    if (pdist_stats_tabela_busca_pkts(indice, &valor) != SUCCESS) {
			return SNMP_ERR_NOSUCHNAME;
		    }
		    snmp_set_var_typed_value(var, ASN_GAUGE, (u_char *)&valor, sizeof(valor));
		    break;

		case COLUMN_PROTOCOLDISTSTATSOCTETS:
		    if (pdist_stats_tabela_busca_octets(indice, &valor) != SUCCESS) {
			return SNMP_ERR_NOSUCHNAME;
		    }
		    snmp_set_var_typed_value(var, ASN_GAUGE, (u_char *)&valor, sizeof(valor));
		    break;

		default:
		    /*
		     * We shouldn't get here
		     */
		    snmp_log(LOG_ERR,
			     "problem encountered in protocolDistStatsTable_handler: unknown column\n");
            }
            break;

        case MODE_SET_RESERVE1:
            /*
             * set handling...
             */
	    return SNMP_ERR_READONLY;

        default:
            snmp_log(LOG_ERR,
                     "problem encountered in protocolDistStatsTable_handler: unsupported mode\n");
        }
    }

    return SNMP_ERR_NOERROR;
}


/** returns the first data point within the protocolDistControlTable table data.

    Set the my_loop_context variable to the first data point structure
    of your choice (from which you can find the next one).  This could
    be anything from the first node in a linked list, to an integer
    pointer containing the beginning of an array variable.

    Set the my_data_context variable to something to be returned to
    you later that will provide you with the data to return in a given
    row.  This could be the same pointer as what my_loop_context is
    set to, or something different.

    The put_index_data variable contains a list of snmp variable
    bindings, one for each index in your table.  Set the values of
    each appropriately according to the data matching the first row
    and return the put_index_data variable at the end of the function.
*/
netsnmp_variable_list *
protocolDistControlTable_get_first_data_point(void **my_loop_context,
                                              void **my_data_context,
                                              netsnmp_variable_list *put_index_data,
                                              netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    unsigned int	    indice_atual = 0;
    unsigned int	    indice_max = pdist_control_busca_maximo();

    /* test for a valid entry */
    while (pdist_control_testa(indice_atual) != SUCCESS) {
	if (indice_atual < indice_max) {
	    indice_atual++;
	}
	else {
	    /* no more entries */
	    return NULL;
	}
    }

    *my_loop_context = (void *)indice_atual;
    *my_data_context = (void *)indice_atual;

    vptr = put_index_data;

    snmp_set_var_value(vptr, (u_char *)&indice_atual, sizeof(indice_atual));
    vptr = vptr->next_variable;

    return put_index_data;
}

/** functionally the same as protocolDistControlTable_get_first_data_point, but
   my_loop_context has already been set to a previous value and should
   be updated to the next in the list.  For example, if it was a
   linked list, you might want to cast it and the return
   my_loop_context->next.  The my_data_context pointer should be set
   to something you need later and the indexes in put_index_data
   updated again. */

netsnmp_variable_list *
protocolDistControlTable_get_next_data_point(void **my_loop_context,
                                             void **my_data_context,
                                             netsnmp_variable_list *put_index_data,
                                             netsnmp_iterator_info *mydata)
{
    netsnmp_variable_list   *vptr;
    unsigned int	    indice_atual = (unsigned int)*my_loop_context + 1;
    unsigned int	    indice_max = pdist_control_busca_maximo();

    /* test for a valid entry */
    while (pdist_control_testa(indice_atual) != SUCCESS) {
	if (indice_atual < indice_max) {
	    indice_atual++;
	}
	else {
	    /* no more entries */
	    return NULL;
	}
    }

    *my_loop_context = (void *)indice_atual;
    *my_data_context = (void *)indice_atual;

    vptr = put_index_data;

    snmp_set_var_value(vptr, (u_char *)&indice_atual, sizeof(indice_atual));
    vptr = vptr->next_variable;

    return put_index_data;
}

/** handles requests for the protocolDistControlTable table, if anything else needs to be done */
int
protocolDistControlTable_handler(netsnmp_mib_handler *handler,
                                 netsnmp_handler_registration *reginfo,
                                 netsnmp_agent_request_info *reqinfo,
                                 netsnmp_request_info *requests)
{
    /* IF-MIB::ifIndex.n == .1.3.6.1.2.1.2.2.1.1.n */
    char			char_buffer[64];
    oid				ifindex_oid[] = {1, 3, 6, 1, 2, 1, 2, 2, 1, 1, 0};
    netsnmp_request_info	*request;
    netsnmp_table_request_info	*table_info;
    netsnmp_variable_list	*var;
    uint32_t			indice;
    uint32_t			valor;
    int				valor_sinal;

    for (request = requests; request; request = request->next) {
        var = request->requestvb;
        if (request->processed != 0) {
            continue;
	}

        /*
         * perform anything here that you need to do before each
         * request is processed.
         */

        /*
         * the following extracts the my_data_context pointer set in
         * the loop functions above.  You can then use the results to
         * help return data for the columns of the protocolDistControlTable table in question
         */
	indice = (uint32_t)netsnmp_extract_iterator_context(request);
        if (indice == 0) {
	    /* DUMB! */
            if (reqinfo->mode == MODE_GET) {
                netsnmp_set_request_error(reqinfo, request, SNMP_NOSUCHINSTANCE);
                continue;
            }
            /*
             * XXX: no row existed, if you support creation and this is a
             * set, start dealing with it here, else continue
             */

	    /* FIXME */
        }

	ifindex_oid[10] = (oid)indice;

        /*
         * extracts the information about the table from the request
         */
        table_info = netsnmp_extract_table_info(request);
        /*
         * table_info->colnum contains the column number requested
         */
        /*
         * table_info->indexes contains a linked list of snmp variable
         * bindings for the indexes of the table.  Values in the list
         * have been set corresponding to the indexes of the
         * request
         */
        if (table_info == NULL) {
            continue;
        }

        switch (reqinfo->mode) {
            /*
             * the table_iterator helper should change all GETNEXTs
             * into GETs for you automatically, so you don't have to
             * worry about the GETNEXT case.  Only GETs and SETs need
             * to be dealt with here
             */
        case MODE_GET:
            switch (table_info->colnum) {
		case COLUMN_PROTOCOLDISTCONTROLDATASOURCE:
		    snmp_set_var_typed_value(var, ASN_OBJECT_ID, (u_char *)ifindex_oid, sizeof(ifindex_oid));
		    break;

		case COLUMN_PROTOCOLDISTCONTROLDROPPEDFRAMES:
		    if (pdist_control_busca_droppedframes(indice, &valor) != SUCCESS) {
			return SNMP_ERR_NOSUCHNAME;
		    }
		    snmp_set_var_typed_value(var, ASN_COUNTER, (u_char *)&valor, sizeof(valor));
		    break;

		case COLUMN_PROTOCOLDISTCONTROLCREATETIME:
		    if (pdist_control_busca_createtime(indice, &valor) != SUCCESS) {
			return SNMP_ERR_NOSUCHNAME;
		    }
		    snmp_set_var_typed_value(var, ASN_TIMETICKS, (u_char *)&valor, sizeof(valor));
		    break;

		case COLUMN_PROTOCOLDISTCONTROLOWNER:
		    valor = pdist_control_busca_owner(indice, char_buffer, sizeof(char_buffer));
		    if (valor == 0) {
			/* error */
			return SNMP_ERR_NOSUCHNAME;
		    }
		    snmp_set_var_typed_value(var, ASN_OCTET_STR, (u_char *)char_buffer, valor);
		    break;

		case COLUMN_PROTOCOLDISTCONTROLSTATUS:
		    valor_sinal = pdist_control_busca_status(indice);
		    if (valor_sinal < 0) {
			return SNMP_ERR_NOSUCHNAME;
		    }

		    snmp_set_var_typed_value(var, ASN_INTEGER, (u_char *)&valor_sinal,
			    sizeof(valor_sinal));
		    break;

		default:
		    /*
		     * We shouldn't get here
		     */
		    snmp_log(LOG_ERR,
			     "problem encountered in protocolDistControlTable_handler: unknown column\n");
            }
            break;

        case MODE_SET_RESERVE1:
            /*
             * set handling...
             */

	    /* FIXME */

        default:
            snmp_log(LOG_ERR,
                     "problem encountered in protocolDistControlTable_handler: unsupported mode\n");
        }
    }
    return SNMP_ERR_NOERROR;
}

