/*
 * Ramon - A RMON2 Network Monitoring Agent
 * Copyright (C) 2003 Ricardo Nabinger Sanchez
 *
 * This file is part of Ramon, a network monitoring agent which implements
 * the MIB proposed in RFC-2021.
 *
 * Ramon is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
 *
 * Ramon is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with program; see the file COPYING. If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */
#ifndef NLMATRIX_H
#define NLMATRIX_H

/*
 * function declarations
 */
void init_nlMatrix(void);
void initialize_table_hlMatrixControlTable(void);
Netsnmp_Node_Handler hlMatrixControlTable_handler;

Netsnmp_First_Data_Point hlMatrixControlTable_get_first_data_point;
Netsnmp_Next_Data_Point hlMatrixControlTable_get_next_data_point;
void initialize_table_nlMatrixDSTable(void);
Netsnmp_Node_Handler nlMatrixDSTable_handler;

Netsnmp_First_Data_Point nlMatrixDSTable_get_first_data_point;
Netsnmp_Next_Data_Point nlMatrixDSTable_get_next_data_point;
void initialize_table_nlMatrixTopNTable(void);
Netsnmp_Node_Handler nlMatrixTopNTable_handler;

Netsnmp_First_Data_Point nlMatrixTopNTable_get_first_data_point;
Netsnmp_Next_Data_Point nlMatrixTopNTable_get_next_data_point;
void initialize_table_nlMatrixSDTable(void);
Netsnmp_Node_Handler nlMatrixSDTable_handler;

Netsnmp_First_Data_Point nlMatrixSDTable_get_first_data_point;
Netsnmp_Next_Data_Point nlMatrixSDTable_get_next_data_point;
void initialize_table_nlMatrixTopNControlTable(void);
Netsnmp_Node_Handler nlMatrixTopNControlTable_handler;

Netsnmp_First_Data_Point nlMatrixTopNControlTable_get_first_data_point;
Netsnmp_Next_Data_Point nlMatrixTopNControlTable_get_next_data_point;

/*
 * column number definitions for table hlMatrixControlTable
 */
#define COLUMN_HLMATRIXCONTROLINDEX			1
#define COLUMN_HLMATRIXCONTROLDATASOURCE		2
#define COLUMN_HLMATRIXCONTROLNLDROPPEDFRAMES		3
#define COLUMN_HLMATRIXCONTROLNLINSERTS			4
#define COLUMN_HLMATRIXCONTROLNLDELETES			5
#define COLUMN_HLMATRIXCONTROLNLMAXDESIREDENTRIES	6
#define COLUMN_HLMATRIXCONTROLALDROPPEDFRAMES		7
#define COLUMN_HLMATRIXCONTROLALINSERTS			8
#define COLUMN_HLMATRIXCONTROLALDELETES			9
#define COLUMN_HLMATRIXCONTROLALMAXDESIREDENTRIES	10
#define COLUMN_HLMATRIXCONTROLOWNER			11
#define COLUMN_HLMATRIXCONTROLSTATUS			12

/*
 * column number definitions for table nlMatrixDSTable
 */
#define COLUMN_NLMATRIXDSTIMEMARK	1
#define COLUMN_NLMATRIXDSSOURCEADDRESS	2
#define COLUMN_NLMATRIXDSDESTADDRESS	3
#define COLUMN_NLMATRIXDSPKTS		4
#define COLUMN_NLMATRIXDSOCTETS		5
#define COLUMN_NLMATRIXDSCREATETIME	6

/*
 * column number definitions for table nlMatrixTopNTable
 */
#define COLUMN_NLMATRIXTOPNINDEX			1
#define COLUMN_NLMATRIXTOPNPROTOCOLDIRLOCALINDEX	2
#define COLUMN_NLMATRIXTOPNSOURCEADDRESS		3
#define COLUMN_NLMATRIXTOPNDESTADDRESS			4
#define COLUMN_NLMATRIXTOPNPKTRATE			5
#define COLUMN_NLMATRIXTOPNREVERSEPKTRATE		6
#define COLUMN_NLMATRIXTOPNOCTETRATE			7
#define COLUMN_NLMATRIXTOPNREVERSEOCTETRATE		8

/*
 * column number definitions for table nlMatrixSDTable
 */
#define COLUMN_NLMATRIXSDTIMEMARK		1
#define COLUMN_NLMATRIXSDSOURCEADDRESS		2
#define COLUMN_NLMATRIXSDDESTADDRESS		3
#define COLUMN_NLMATRIXSDPKTS			4
#define COLUMN_NLMATRIXSDOCTETS			5
#define COLUMN_NLMATRIXSDCREATETIME		6

/*
 * column number definitions for table nlMatrixTopNControlTable
 */
#define COLUMN_NLMATRIXTOPNCONTROLINDEX			1
#define COLUMN_NLMATRIXTOPNCONTROLMATRIXINDEX		2
#define COLUMN_NLMATRIXTOPNCONTROLRATEBASE		3
#define COLUMN_NLMATRIXTOPNCONTROLTIMEREMAINING		4
#define COLUMN_NLMATRIXTOPNCONTROLGENERATEDREPORTS	5
#define COLUMN_NLMATRIXTOPNCONTROLDURATION		6
#define COLUMN_NLMATRIXTOPNCONTROLREQUESTEDSIZE		7
#define COLUMN_NLMATRIXTOPNCONTROLGRANTEDSIZE		8
#define COLUMN_NLMATRIXTOPNCONTROLSTARTTIME		9
#define COLUMN_NLMATRIXTOPNCONTROLOWNER			10
#define COLUMN_NLMATRIXTOPNCONTROLSTATUS		11
#endif                          /* NLMATRIX_H */
