/*
 * Ramon - A RMON2 Network Monitoring Agent
 * Copyright (C) 2003 Ricardo Nabinger Sanchez
 *
 * This file is part of Ramon, a network monitoring agent which implements
 * the MIB proposed in RFC-2021.
 *
 * Ramon is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
 *
 * Ramon is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with program; see the file COPYING. If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */
#ifndef PROBECONFIG_H
#define PROBECONFIG_H

/*
 * function declarations
 */
void init_probeConfig(void);
void initialize_table_trapDestTable(void);
Netsnmp_Node_Handler trapDestTable_handler;

Netsnmp_First_Data_Point trapDestTable_get_first_data_point;
Netsnmp_Next_Data_Point trapDestTable_get_next_data_point;
void initialize_table_serialConnectionTable(void);
Netsnmp_Node_Handler serialConnectionTable_handler;

Netsnmp_First_Data_Point serialConnectionTable_get_first_data_point;
Netsnmp_Next_Data_Point serialConnectionTable_get_next_data_point;
void initialize_table_serialConfigTable(void);
Netsnmp_Node_Handler serialConfigTable_handler;

Netsnmp_First_Data_Point serialConfigTable_get_first_data_point;
Netsnmp_Next_Data_Point serialConfigTable_get_next_data_point;
void initialize_table_netConfigTable(void);
Netsnmp_Node_Handler netConfigTable_handler;

Netsnmp_First_Data_Point netConfigTable_get_first_data_point;
Netsnmp_Next_Data_Point netConfigTable_get_next_data_point;

/*
 * column number definitions for table trapDestTable
 */
#define COLUMN_TRAPDESTINDEX		1
#define COLUMN_TRAPDESTCOMMUNITY	2
#define COLUMN_TRAPDESTPROTOCOL		3
#define COLUMN_TRAPDESTADDRESS		4
#define COLUMN_TRAPDESTOWNER		5
#define COLUMN_TRAPDESTSTATUS		6

/*
 * column number definitions for table serialConnectionTable
 */
#define COLUMN_SERIALCONNECTINDEX		1
#define COLUMN_SERIALCONNECTDESTIPADDRESS	2
#define COLUMN_SERIALCONNECTTYPE		3
#define COLUMN_SERIALCONNECTDIALSTRING		4
#define COLUMN_SERIALCONNECTSWITCHCONNECTSEQ	5
#define COLUMN_SERIALCONNECTSWITCHDISCONNECTSEQ	6
#define COLUMN_SERIALCONNECTSWITCHRESETSEQ	7
#define COLUMN_SERIALCONNECTOWNER		8
#define COLUMN_SERIALCONNECTSTATUS		9

/*
 * column number definitions for table serialConfigTable
 */
#define COLUMN_SERIALMODE		1
#define COLUMN_SERIALPROTOCOL		2
#define COLUMN_SERIALTIMEOUT		3
#define COLUMN_SERIALMODEMINITSTRING	4
#define COLUMN_SERIALMODEMHANGUPSTRING	5
#define COLUMN_SERIALMODEMCONNECTRESP	6
#define COLUMN_SERIALMODEMNOCONNECTRESP	7
#define COLUMN_SERIALDIALOUTTIMEOUT	8
#define COLUMN_SERIALSTATUS		9

/*
 * column number definitions for table netConfigTable
 */
#define COLUMN_NETCONFIGIPADDRESS	1
#define COLUMN_NETCONFIGSUBNETMASK	2
#define COLUMN_NETCONFIGSTATUS		3
#endif                          /* PROBECONFIG_H */
