/*
 * Ramon - A RMON2 Network Monitoring Agent
 * Copyright (C) 2003 Ricardo Nabinger Sanchez
 *
 * This file is part of Ramon, a network monitoring agent which implements
 * the MIB proposed in RFC-2021.
 *
 * Ramon is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
 *
 * Ramon is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with program; see the file COPYING. If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */
#ifndef PROTOCOLDIR_H
#define PROTOCOLDIR_H

/*
 * function declarations
 */
void init_protocolDir(void);
void initialize_table_protocolDirTable(void);
Netsnmp_Node_Handler protocolDirTable_handler;

Netsnmp_First_Data_Point protocolDirTable_get_first_data_point;
Netsnmp_Next_Data_Point protocolDirTable_get_next_data_point;

/*
 * column number definitions for table protocolDirTable
 */
#define COLUMN_PROTOCOLDIRID		    1
#define COLUMN_PROTOCOLDIRPARAMETERS	    2
#define COLUMN_PROTOCOLDIRLOCALINDEX	    3
#define COLUMN_PROTOCOLDIRDESCR		    4
#define COLUMN_PROTOCOLDIRTYPE		    5
#define COLUMN_PROTOCOLDIRADDRESSMAPCONFIG  6
#define COLUMN_PROTOCOLDIRHOSTCONFIG	    7
#define COLUMN_PROTOCOLDIRMATRIXCONFIG	    8
#define COLUMN_PROTOCOLDIROWNER		    9
#define COLUMN_PROTOCOLDIRSTATUS	    10
#endif                          /* PROTOCOLDIR_H */
