/*
 * Ramon - A RMON2 Network Monitoring Agent
 * Copyright (C) 2003 Ricardo Nabinger Sanchez
 *
 * This file is part of Ramon, a network monitoring agent which implements
 * the MIB proposed in RFC-2021.
 *
 * Ramon is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the
 * Free Software Foundation; either version 2, or (at your option) any
 * later version.
 *
 * Ramon is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
 * for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with program; see the file COPYING. If not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.iterate.conf,v 5.5 2002/12/16 22:50:18 hardaker Exp $
 */
#ifndef USRHISTORY_H
#define USRHISTORY_H

/*
 * function declarations
 */
void init_usrHistory(void);
void initialize_table_usrHistoryObjectTable(void);
Netsnmp_Node_Handler usrHistoryObjectTable_handler;

Netsnmp_First_Data_Point usrHistoryObjectTable_get_first_data_point;
Netsnmp_Next_Data_Point usrHistoryObjectTable_get_next_data_point;
void initialize_table_usrHistoryControlTable(void);
Netsnmp_Node_Handler usrHistoryControlTable_handler;

Netsnmp_First_Data_Point usrHistoryControlTable_get_first_data_point;
Netsnmp_Next_Data_Point usrHistoryControlTable_get_next_data_point;
void initialize_table_usrHistoryTable(void);
Netsnmp_Node_Handler usrHistoryTable_handler;

Netsnmp_First_Data_Point usrHistoryTable_get_first_data_point;
Netsnmp_Next_Data_Point usrHistoryTable_get_next_data_point;

/*
 * column number definitions for table usrHistoryObjectTable
 */
#define COLUMN_USRHISTORYOBJECTINDEX		1
#define COLUMN_USRHISTORYOBJECTVARIABLE		2
#define COLUMN_USRHISTORYOBJECTSAMPLETYPE	3

/*
 * column number definitions for table usrHistoryControlTable
 */
#define COLUMN_USRHISTORYCONTROLINDEX			1
#define COLUMN_USRHISTORYCONTROLOBJECTS			2
#define COLUMN_USRHISTORYCONTROLBUCKETSREQUESTED	3
#define COLUMN_USRHISTORYCONTROLBUCKETSGRANTED		4
#define COLUMN_USRHISTORYCONTROLINTERVAL		5
#define COLUMN_USRHISTORYCONTROLOWNER			6
#define COLUMN_USRHISTORYCONTROLSTATUS			7

/*
 * column number definitions for table usrHistoryTable
 */
#define COLUMN_USRHISTORYSAMPLEINDEX		1
#define COLUMN_USRHISTORYINTERVALSTART		2
#define COLUMN_USRHISTORYINTERVALEND		3
#define COLUMN_USRHISTORYABSVALUE		4
#define COLUMN_USRHISTORYVALSTATUS		5
#endif                          /* USRHISTORY_H */
